import Navbar from '../Navbar';
import Footer from '../Footer';
import Head from 'next/head';

import { motion } from 'framer-motion';

const Layout = ({ children }) => {
	return (
		<>
			<Head>
				<title>King Tax - Accounting Services</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<main>{children}</main>
			<Footer />
		</>
	);
};

export default Layout;
